exclude: ".venv|test*|.git|epd*"
default_stages: [commit]
fail_fast: false

repos:
  - repo: local
    hooks:
      - id: black-check
        name: black-check
        entry: black .
        language: system
        pass_filenames: false
        always_run: true

  - repo: local
    hooks:
      - id: mypy-check
        name: mypy-check
        entry: mypy .
        language: system
        pass_filenames: false
        always_run: true

  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8
        name: flake8-check
        description: "flake8 is a command-line utility for enforcing style consistency across Python projects."
        entry: flake8
        language: python
        types: [python]
        require_serial: true
        args: ["--config=.flake8"]

  - repo: https://github.com/myint/eradicate
    rev: v2.0.0
    hooks:
      - id: eradicate
        language_version: python3.9
        entry: eradicate
        files: '\.py$'
        args: [ --in-place ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=500']

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.2.1
    hooks:
      - id: python-safety-dependencies-check
        args: [--json, -i 38678]